name: "test itself"
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1 шаг необходим, чтобы использовать экшен из соседней папки
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
